// Package agent defines the application-owned contract for AI Agent execution.
package agent

import "context"

// Message is a text message passed to an Agent run.
type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// Input contains the persisted conversation needed to execute a run.
type Input struct {
	RunID    string
	ChatID   string
	ModelID  string
	Messages []Message
}

// ModelInfo 是可以安全返回给前端的模型目录信息。
// 完整模型名用于下拉展示；厂商 API Key 和 Base URL 始终只保留在服务端。
type ModelInfo struct {
	ID           string `json:"id"`
	ModelName    string `json:"modelName"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	IconURL      string `json:"icon_url"`
}

// ModelCatalog 负责解析前端提交的稳定模型 ID。
type ModelCatalog interface {
	DefaultModelID() string
	ResolveModelID(modelID string) (string, bool)
	Models() []ModelInfo
}

// EventType identifies an event produced during Agent execution.
type EventType string

const (
	EventStarted       EventType = "started"
	EventDelta         EventType = "content_delta"
	EventToolStarted   EventType = "tool_started"
	EventToolCompleted EventType = "tool_completed"
	EventToolFailed    EventType = "tool_failed"
	EventCompleted     EventType = "completed"
)

// ToolEvent contains one model-generated tool call and its current result.
type ToolEvent struct {
	// CallID connects the model's request with the matching tool result.
	CallID string

	// ID is the machine-readable tool name registered with the Agent runtime.
	ID string

	// Name is the human-readable label rendered by the frontend.
	Name string

	// Input is the decoded JSON arguments generated by the model.
	Input any

	// Output is the decoded JSON value returned by the tool.
	Output any

	// Error is present only when the tool invocation failed.
	Error *Failure
}

// Event is the provider-independent stream consumed by the chat module.
type Event struct {
	Type     EventType
	Model    string
	Delta    string
	FullText string
	Tool     *ToolEvent
}

// Failure is a structured Agent failure safe to expose through the IM protocol.
// Cause is retained for server-side diagnostics and is never sent to the client.
type Failure struct {
	Code      string
	Message   string
	Retryable bool
	Cause     error
}

func (e *Failure) Error() string {
	if e.Cause != nil {
		return e.Code + ": " + e.Message + ": " + e.Cause.Error()
	}
	return e.Code + ": " + e.Message
}

// Unwrap exposes the underlying provider error to errors.Is and errors.As.
func (e *Failure) Unwrap() error {
	return e.Cause
}

// Runner executes an Agent run and emits ordered, provider-independent events.
type Runner interface {
	Run(ctx context.Context, input Input, handle func(Event) error) error
	Close() error
}
