# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eterion_agent/agent.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'eterion_agent/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65terion_agent/agent.proto\x12\reterion.agent\"[\n\nRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\x12,\n\x08messages\x18\x03 \x03(\x0b\x32\x1a.eterion.agent.ChatMessage\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xd7\x01\n\x08RunEvent\x12,\n\x07started\x18\x01 \x01(\x0b\x32\x19.eterion.agent.RunStartedH\x00\x12\x34\n\rcontent_delta\x18\x02 \x01(\x0b\x32\x1b.eterion.agent.ContentDeltaH\x00\x12\x30\n\tcompleted\x18\x03 \x01(\x0b\x32\x1b.eterion.agent.RunCompletedH\x00\x12*\n\x06\x66\x61iled\x18\x04 \x01(\x0b\x32\x18.eterion.agent.RunFailedH\x00\x42\t\n\x07payload\"\x1b\n\nRunStarted\x12\r\n\x05model\x18\x01 \x01(\t\"\x1d\n\x0c\x43ontentDelta\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\t\"!\n\x0cRunCompleted\x12\x11\n\tfull_text\x18\x01 \x01(\t\"=\n\tRunFailed\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tretryable\x18\x03 \x01(\x08\x32Q\n\x0c\x41gentService\x12\x41\n\tStreamRun\x12\x19.eterion.agent.RunRequest\x1a\x17.eterion.agent.RunEvent0\x01\x42JZHgithub.com/Infinitefft/Eterion/services/api/internal/gen/agentpb;agentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eterion_agent.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/Infinitefft/Eterion/services/api/internal/gen/agentpb;agentpb'
  _globals['_RUNREQUEST']._serialized_start=44
  _globals['_RUNREQUEST']._serialized_end=135
  _globals['_CHATMESSAGE']._serialized_start=137
  _globals['_CHATMESSAGE']._serialized_end=181
  _globals['_RUNEVENT']._serialized_start=184
  _globals['_RUNEVENT']._serialized_end=399
  _globals['_RUNSTARTED']._serialized_start=401
  _globals['_RUNSTARTED']._serialized_end=428
  _globals['_CONTENTDELTA']._serialized_start=430
  _globals['_CONTENTDELTA']._serialized_end=459
  _globals['_RUNCOMPLETED']._serialized_start=461
  _globals['_RUNCOMPLETED']._serialized_end=494
  _globals['_RUNFAILED']._serialized_start=496
  _globals['_RUNFAILED']._serialized_end=557
  _globals['_AGENTSERVICE']._serialized_start=559
  _globals['_AGENTSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
